#pragma once

#include <QIcon>

namespace smartGraphics3D
{
enum class SIconId
{
    FileNew,
    FileOpen,
    FileSave,
    FileSaveAs,
    FileImport,
    FileExport,
    ProjectArchive,
    PrimitiveBox,
    PrimitiveCylinder,
    PrimitiveCone,
    PrimitiveSphere,
    PrimitiveTorus,
    BooleanUnion,
    BooleanDifference,
    BooleanIntersection,
    Fillet,
    Chamfer,
    Hole,
    Transform,
    Mirror,
    Copy,
    LinearArray,
    PolarArray,
    Delete,
    Undo,
    Redo,
    MeasureStatistics,
    MeasureSubElement,
    MeasureDistance,
    MeasureAngle,
    MeasureSection,
    MeasureExport,
    ViewportScreenshot,
    SnapshotCreate,
    SnapshotRestore,
    SnapshotBranch,
    FitAll,
    FitSelection,
    ViewIsometric,
    ViewFront,
    ViewBack,
    ViewLeft,
    ViewRight,
    ViewTop,
    ViewBottom,
    DisplayWireframe,
    DisplayShaded,
    DisplayShadedEdges,
    DisplayHiddenLine,
    DisplayTransparent,
    Projection,
    ViewSave,
    ViewRestore,
    RotationCenter,
    FreeRotation,
    ClipPlanes,
    ViewportSingle,
    ViewportHorizontal,
    ViewportVertical,
    ViewportFour,
    SyncCamera,
    SyncSelection,
    SelectObject,
    SelectSolid,
    SelectFace,
    SelectEdge,
    SelectVertex,
    SelectAll,
    SelectInvert,
    ProjectUnit,
    UserCoordinateSystem,
    ObjectCoordinateSystem,
    CoordinateSystemList,
    Diagnostics,
    InterfaceScale,
    About,
    SceneGroup,
    SceneCadShape,
    SceneMesh,
    SceneMeasurement,
    SceneCoordinateSystem
};

[[nodiscard]] QIcon applicationIcon();
[[nodiscard]] QIcon iconForAction(SIconId icon_id);
} // namespace smartGraphics3D
